apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: ambassador
    descriptors:
    - key: remote_address
      descriptors:  
      - key: host
        descriptors:
        - key: generic_key
          value: second
          rate_limit:
            unit: second
            requests_per_unit: 25
        - key: generic_key
          value: hour
          rate_limit:
            unit: hour
            requests_per_unit: 1000
