wg-access-server:
  wireguard:
    config:
      privateKey: ***REMOVED***
    service:
      type: LoadBalancer
  persistence:
    enabled: true
  # fullnameOverride: wg
  # nameOverride: wg
  web:
    config:
      adminUsername: admin
      adminPassword: password
  config:
    vpn:
      cidr: 10.13.13.0/28
      allowedIPs:
      - 0.0.0.0/0