apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ctfd
spec:
  hosts:
  - fuck.loopset.net
  gateways:
  - ctfd-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        host: ctfd