apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 7.16.3
  http:
    tls: 
      selfSignedCertificate:
        disabled: false
  nodeSets:
  - name: default
    count: 3
    config:
      xpack.security.authc.api_key.enabled: true
    podTemplate:
      spec:  
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        securityContext:
          fsGroup: 1000
          runAsUser: 1000


