apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic
spec:
  version: 7.16.3
  count: 1
  elasticsearchRef:
    name: elastic
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      # automountServiceAccountToken: true 
      securityContext:
          fsGroup: 1000
          runAsUser: 1000