apiVersion: v2
name: istio-system
version: 0.1.0
appVersion: 1.12.1
dependencies:
- name: base
  version: 1.12.1
  repository: https://istio-release.storage.googleapis.com/charts
- name: istiod
  version: 1.12.1
  repository: https://istio-release.storage.googleapis.com/charts
