edge-stack:  
  emissary-ingress:
    envRaw: ""
    # envRaw: |
    #   - name: REDIS_URL
    #     value: redis-master.redis:6379
    #   {{- if and .Values.licenseKey.secretName }}
    #   - name: AMBASSADOR_AES_SECRET_NAME
    #     value: {{ .Values.licenseKey.secretName }}
    #   {{- end }}
    #image:
      #tag: 2.0.5
    createDefaultListeners: true
    service:
      externalTrafficPolicy: Local
      ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
      # - name: nsjail
      #   port: 9000
      #   targetPort: 9000
      #   protocol: TCP
    resolvers:
      endpoint:
        create: true
        name: endpoint
    replicaCount: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
    agent:
      enabled: false    
    env:
      REDIS_URL: redis-master.redis:6379
  rateLimit:
    create: false 
  createDevPortalMappings: false
  redis:
    create: false
