- name: Install Helm Repos
  hosts: localhost
  tasks:
    - name: jetstack
      kubernetes.core.helm_repository:
        name: jetstack
        url: https://charts.jetstack.io

    - name: istio
      kubernetes.core.helm_repository:
        name: istio
        url: https://istio-release.storage.googleapis.com/charts

    - name: bitnami
      kubernetes.core.helm_repository:
        name: bitnami
        url: https://charts.bitnami.com/bitnami
        
    - name: elastic
      kubernetes.core.helm_repository:
        name: elastic
        url: https://helm.elastic.co