- hosts: haproxy
  user: ctf
  gather_facts: no
  tasks:
  - name: Copy haproxy.cfg
    ansible.builtin.copy:
      src: ./haproxy/haproxy.cfg
      dest: ~/haproxy/
      mode: '0600'

  - name: Build HAProxy images and start containers
    community.docker.docker_compose:
      project_src: ~/haproxy/
      build: yes
      nocache: yes
      state: present