- hosts: haproxy
  user: ctf
  tasks:
  - name: Update repo and install docker-compose
    apt:
      name: docker-compose
      state: latest
      update_cache: yes
    become: yes

  - name: >- 
      The stackdriver agent is the Google Cloud Platform monitoring agent - it provides various analytics on the 
      host including but not limited CPU, Memory, and Disk utilization. First, download a script that adds the
      agent's repository to /etc/apt/sources.list
    get_url:
      url: https://dl.google.com/cloudagents/add-monitoring-agent-repo.sh
      dest: /tmp/add-monitoring-agent-repo.sh
      mode: 0750
    become: yes

  - name: Execute the script to add the stackdriver-agent respository /etc/apt/sources.list
    command:
      chdir: /tmp
      cmd: bash add-monitoring-agent-repo.sh
    become: yes

  - name: Install the stackdriver-agent package
    apt:
      name: stackdriver-agent
      state: present
      update_cache: yes 
    become: yes

  - name: Start the stackdriver monitoring agent
    service:
      name: stackdriver-agent
      state: restarted
    become: yes

  - name: Add ctf user to docker group
    user:
      name: ctf
      #password: "{{ lookup('community.general.lastpass', 'ctf_user_pass', field='password') | password_hash('sha512') }}"
      groups: docker
      append: yes
    become: yes

  - name: reset ssh connection to allow user changes to affect 'current login user'
    meta: reset_connection

  - name: Copy haproxy.cfg
    ansible.builtin.copy:
      src: ./haproxy/haproxy.cfg
      dest: ~/haproxy/
      mode: '0600'

  - name: Copy docker-compose.yml
    ansible.builtin.copy:
      src: ./haproxy/docker-compose.yml
      dest: ~/haproxy/
      mode: '0600'

  - name: Copy Dockerfile
    ansible.builtin.copy:
      src: ./haproxy/Dockerfile
      dest: ~/haproxy/
      mode: '0600'

  - name: Build HAProxy images and start containers
    community.docker.docker_compose:
      project_src: ~/haproxy/
      build: yes
      nocache: yes
      state: present
